spring.application.name=emotionPlatform
spring.datasource.url=jdbc:postgresql://localhost:5432/platform_emotion_db
spring.datasource.username=postgres
spring.datasource.password=h62:!-Wy(/

# spring.jpa.hibernate.ddl-auto=validate: Flyway gestisce il database, Hibernate solo le entity
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# permette a Flyway di eseguire gli script
spring.flyway.enabled=true
# Dice a Hibernate che si sta usando postgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
